porto7:
  test_ratio: 0.2
  validation_ratio: 0.1
  delimiter: " "
  min_input_length: 10
  max_input_length: 14
  test_input_length: 10
  test_prediction_length: 5
  batch_size: 256
  device: cuda
  max_epochs: 5
  block_size: 24
  learning_rate: 5.e-3
  weight_decay: 8.e-3
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 100
  lr_decay_iters: 20000
  min_lr: 5.e-8
  seed: 42
  data_dir: ./data
  dataset: porto7
  n_layer: 12
  n_head: 4
  n_embd: 512
  bias: False
  dropout: 0
  model_checkpoint_directory: ./models/
  train_from_checkpoint_if_exist: False
  custom_initialization: False
  patience: 3
porto8:
  test_ratio: 0.2
  validation_ratio: 0.1
  delimiter: " "
  min_input_length: 10
  max_input_length: 14
  test_input_length: 10
  test_prediction_length: 5
  batch_size: 256
  device: cuda
  max_epochs: 4
  block_size: 24
  learning_rate: 5.e-4
  weight_decay: 5.e-3
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 200
  lr_decay_iters: 40000
  min_lr: 1.e-8
  seed: 42
  data_dir: ./data
  dataset: porto8
  n_layer: 12
  n_head: 4
  n_embd: 512
  bias: False
  dropout: 0
  model_checkpoint_directory: ./models/
  train_from_checkpoint_if_exist: False
  custom_initialization: False
  patience: 3
porto9:
  test_ratio: 0.2
  validation_ratio: 0.1
  delimiter: " "
  min_input_length: 10
  max_input_length: 14
  test_input_length: 10
  test_prediction_length: 5
  batch_size: 256
  device: cuda
  max_epochs: 3
  block_size: 24
  learning_rate: 1.e-3
  weight_decay: 5.e-3
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 400
  lr_decay_iters: 80000
  min_lr: 5.e-9
  seed: 42
  data_dir: ./data
  dataset: porto9
  n_layer: 12
  n_head: 4
  n_embd: 512
  bias: False
  dropout: 0
  model_checkpoint_directory: ./models/
  train_from_checkpoint_if_exist: False
  custom_initialization: False
  patience: 3
rome7:
  test_ratio: 0.2
  validation_ratio: 0.1
  delimiter: " "
  min_input_length: 10
  max_input_length: 14
  test_input_length: 10
  test_prediction_length: 5
  batch_size: 256
  device: cuda
  max_epochs: 10
  block_size: 24
  learning_rate: 5.e-4
  weight_decay: 5.e-3
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 100
  lr_decay_iters: 10000
  min_lr: 5.e-8
  seed: 42
  data_dir: ./data
  dataset: rome7
  n_layer: 12
  n_head: 4
  n_embd: 512
  bias: False
  dropout: 0
  model_checkpoint_directory: ./models/
  train_from_checkpoint_if_exist: False
  custom_initialization: False
  patience: 3
rome8:
  test_ratio: 0.2
  validation_ratio: 0.1
  delimiter: " "
  min_input_length: 10
  max_input_length: 14
  test_input_length: 10
  test_prediction_length: 5
  batch_size: 256
  device: cuda
  max_epochs: 10
  block_size: 24
  learning_rate: 5.e-4
  weight_decay: 5.e-3
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 200
  lr_decay_iters: 24000
  min_lr: 1.e-8
  seed: 42
  data_dir: ./data
  dataset: rome8
  n_layer: 12
  n_head: 4
  n_embd: 512
  bias: False
  dropout: 0
  model_checkpoint_directory: ./models/
  train_from_checkpoint_if_exist: False
  custom_initialization: False
  patience: 3
rome9:
  test_ratio: 0.2
  validation_ratio: 0.1
  delimiter: " "
  min_input_length: 10
  max_input_length: 14
  test_input_length: 10
  test_prediction_length: 5
  batch_size: 256
  device: cuda
  max_epochs: 8
  block_size: 24
  learning_rate: 1.e-3
  weight_decay: 5.e-3
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 400
  lr_decay_iters: 60000
  min_lr: 5.e-9
  seed: 42
  data_dir: ./data
  dataset: rome9
  n_layer: 12
  n_head: 4
  n_embd: 512
  bias: False
  dropout: 0
  model_checkpoint_directory: ./models/
  train_from_checkpoint_if_exist: False
  custom_initialization: False
  patience: 3
geolife7:
  test_ratio: 0.2
  validation_ratio: 0.1
  delimiter: " "
  min_input_length: 10
  max_input_length: 14
  test_input_length: 10
  test_prediction_length: 5
  batch_size: 256
  device: cuda
  max_epochs: 10
  block_size: 24
  learning_rate: 5.e-4
  weight_decay: 2.e-3
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 100
  lr_decay_iters: 12000
  min_lr: 2.e-8
  seed: 42
  data_dir: ./data
  dataset: geolife7
  n_layer: 12
  n_head: 4
  n_embd: 512
  bias: False
  dropout: 0
  model_checkpoint_directory: ./models/
  train_from_checkpoint_if_exist: False
  custom_initialization: False
  patience: 3
geolife8:
  test_ratio: 0.2
  validation_ratio: 0.1
  delimiter: " "
  min_input_length: 10
  max_input_length: 14
  test_input_length: 10
  test_prediction_length: 5
  batch_size: 256
  device: cuda
  max_epochs: 10
  block_size: 24
  learning_rate: 5.e-4
  weight_decay: 5.e-3
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 200
  lr_decay_iters: 24000
  min_lr: 1.e-8
  seed: 42
  data_dir: ./data
  dataset: geolife8
  n_layer: 12
  n_head: 4
  n_embd: 512
  bias: False
  dropout: 0
  model_checkpoint_directory: ./models/
  train_from_checkpoint_if_exist: False
  custom_initialization: False
  patience: 3
geolife9:
  test_ratio: 0.2
  validation_ratio: 0.1
  delimiter: " "
  min_input_length: 10
  max_input_length: 14
  test_input_length: 10
  test_prediction_length: 5
  batch_size: 256
  device: cuda
  max_epochs: 6
  block_size: 24
  learning_rate: 5.e-3
  weight_decay: 1.e-2
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0
  decay_lr: True
  warmup_iters: 400
  lr_decay_iters: 60000
  min_lr: 1.e-9
  seed: 42
  data_dir: ./data
  dataset: geolife9
  n_layer: 12
  n_head: 4
  n_embd: 512
  bias: False
  dropout: 0
  model_checkpoint_directory: ./models/
  train_from_checkpoint_if_exist: False
  custom_initialization: False
  patience: 3