name: trajlearn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip:
    - transformers==4.44.1
    - numpy==1.26.4
    - pandas==2.2.2
    - h3==4.1.2
    - torch==2.3.0
    - geojson==3.0.1
    - geopandas==1.0.1
    - geopy==2.4.1
    - matplotlib==3.9.0
    - nltk==3.8.1
    - PyYAML==6.0.1